### ISSUE TITLE
Not picking up sensitivity correctly

### ISSUE THREAD

**Issue by westerlind** [austinnixholm/ThreeFingerDrag#2]
First, thanks a lot for creating this!
It is the first actually functioning implementation I have seen for this feature on Windows, and it is probably the macOS feature I have personally been missing the most while using Windows as someone who is mostly a Mac user.

The problem on my Windows laptop though, is that the sensitivity first was at a much much lower than when simply moving the pointer around.
I then tried to change the sensitivity in the Windows settings to see if that would change anything, and it turns out that when I change the touchpad sensitivity nothing happens at all, but when I instead change the mouse sensitivity to max, the three-finger-drag becomes much better (but still slower than moving the pointer normally).
So, that does help to make it usable for me, but I would need to decrease the mouse speed to half when actually using a mouse now :)

So the issues on my machine is that the sensitivity is taken from the mouse rather than the touchpad, and that it also seems to still read it as slower than it is set to be.

The laptop i tried this on is a Thinkpad X1 Gen 7.
Just ask if you need more info about it.

**Comment by austinnixholm** [comment]
Hey, thanks for the heads up! This problem is caused by the method I am using to simulate cursor movement, which sends out mouse movement events (which are affected by the system's mouse speed setting, oops). 

This was an oversight and I've just released [version 1.0.5](https://github.com/austinnixholm/ThreeFingerDrag/releases/tag/v1.0.5) which includes the fix that behavior.

Please feel free try it out and let me know if you're still encountering this issue. 

Another thing I should note is that I've only been able to test this software on one touchpad which is my Apple Magic Trackpad 2. This might explain the overall slow speed on your device, as I'm unsure of the difference between the raw input from different touchpad drivers. 

I will look into getting access to some other kinds of precision touchpads for additional testing, which will hopefully lead to the program working well for all touchpads. Until then, I will be adding a manually adjustable gesture speed in the next version.

**Comment by westerlind** [comment]
Thanks!
Its much better now with version 1.0.5 :) 
I do feel like it might be good to also be able to fine tune it manually, so it sounds great that you are working on that too.
For some reason I get the feeling that I might want it to be somewhat faster than the normal pointer speed, as a consequence of the touchpad being so small on most PC laptops compared to a Mac.
Another way of solving most of the problem with a smaller touchpad with this feature is to implement something like the ability you have with Apples version of this to release your fingers for maybe half a second and still be able to continue dragging when you put the fingers down again in better position on the touchpad (and Apples version of that also lets you stop dragging fast by first releasing the fingers and than tap fast on the touchpad, so that you are not slowed down by the delay that comes from allowing to move the fingers to a new position and continue dragging)

Anyway, the main problem that this issue was about is really solved now, so thanks again for that!

**Comment by austinnixholm** [comment]
Happy to hear that the primary issue was fixed!

I think I understand what you mean by that feature - do you mean being able to continue your text selection/highlight by lifting and starting another three-finger-drag gesture? If so, this was something I attempted to implement earlier on in the project but had an issue facilitating that so I moved forward. However, it's 100% possible I'll definitely get that added soon.

As promised, the [latest version](https://github.com/austinnixholm/ThreeFingerDrag/releases/latest) features a Settings menu, which lets you manually configure your gesture speed & more. 

Hope this helps with usability for you, and I appreciate your feedback & interest.

**Comment by westerlind** [comment]
Yes, that's exactly what I mean, so then we agree that this would be a nice feature, if it is possible to implement 🙂 

Thanks for all this! You have made using Windows on a laptop much much nicer than before!
